name:   CI/CD pipeline

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: express-tests/
        run: pnpm i && npx prisma generate

      - name: Run tests
        working-directory: express-tests/
        run: pnpm run test
        